[project]
name = "aivisspeechfastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "lameenc>=1.8.1",
    "uvicorn>=0.34.0",
]
